### ISSUE TITLE
Handle # and other symbols in post titles

### ISSUE THREAD

**Issue by spencerthayer** [beardog108/MicroTXT#1] opened 2016-11-30 18:56 UTC
I get the following error on a fresh installation when posting the first test.

> Warning: file_put_contents(posts/Test Post #666 - 2.html): failed to open stream: No such file or directory in /PATH/submit.php on line 107
> 
> Warning: Cannot modify header information - headers already sent by (output started at /PATH/submit.php:107) in /PATH/submit.php on line 114

**Comment by beardog108** [comment] 2016-11-30 22:38
Hey @spencerthayer, thanks for taking the time to report your issue.

Its nice to know that someone is taking an interest in this.

I believe the problem is '#' Is in your post title, though this is my fault for not correctly handling that.

I'll fix this problem as soon as I can.  :+1:

**Comment by beardog108** [comment] 2016-11-30 23:19
Whoops, looks like the posts folder doesn't exist. Sorry! Fixing this now.

**Comment by beardog108** [comment] 2016-11-30 23:49
Ok, I have to go now, but I've fixed the # issue by filtering it out. 

Other symbols may still break, i'll look at this further ASAP.

I also added the posts directory, which was missing for some reason.

Sorry for the inconvenience and thanks again for the report.

**Comment by beardog108** [comment] 2016-12-01 06:22
Ok, I fixed the other symbols that break now too (& and .).

I'm closing this issue unless more symbols that break are discovered.

:+1:

**Closed by beardog108** 2016-12-01 06:22 UTC
Labels: bug

**Comment by spencerthayer** [comment] 2016-12-01 17:27
Thanks!
